DO $$ BEGIN CREATE TYPE phone_platform AS ENUM ('ANDROID','IOS','FEATURE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE debt_status AS ENUM ('ACTIVE','PAID','CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE products ADD COLUMN IF NOT EXISTS platform phone_platform;
ALTER TABLE products ADD COLUMN IF NOT EXISTS legacy_code varchar(40);
CREATE UNIQUE INDEX IF NOT EXISTS products_legacy_code_uidx ON products(legacy_code);
ALTER TABLE inventory_units ADD COLUMN IF NOT EXISTS icloud varchar(30);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cash_amount bigint NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS card_amount bigint NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS debt_due_date date;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS warranty_expires_at date;
CREATE TABLE IF NOT EXISTS debts (id bigserial PRIMARY KEY,sale_id bigint NOT NULL UNIQUE REFERENCES sales(id),total_amount bigint NOT NULL,paid_amount bigint NOT NULL,remaining_amount bigint NOT NULL,due_date date NOT NULL,status debt_status NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS debts_status_due_idx ON debts(status,due_date);
CREATE TABLE IF NOT EXISTS debt_payments (id bigserial PRIMARY KEY,debt_id bigint NOT NULL REFERENCES debts(id),amount bigint NOT NULL,cash_amount bigint NOT NULL DEFAULT 0,card_amount bigint NOT NULL DEFAULT 0,notes text,received_by bigint REFERENCES users(id),paid_at timestamptz NOT NULL DEFAULT now(),status record_status NOT NULL DEFAULT 'ACTIVE');
CREATE INDEX IF NOT EXISTS debt_payments_debt_idx ON debt_payments(debt_id,paid_at);
CREATE TABLE IF NOT EXISTS partners (id bigserial PRIMARY KEY,name varchar(120) NOT NULL UNIQUE,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS partner_phones (id bigserial PRIMARY KEY,partner_id bigint NOT NULL REFERENCES partners(id),product_id bigint NOT NULL REFERENCES products(id),given_amount bigint NOT NULL,received_amount bigint NOT NULL DEFAULT 0,remaining_amount bigint NOT NULL,due_date date,customer_name varchar(160),customer_phone varchar(20),warranty_days integer NOT NULL DEFAULT 0,notes text,status varchar(30) NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS partner_phones_partner_idx ON partner_phones(partner_id,status);
CREATE TABLE IF NOT EXISTS partner_payments (id bigserial PRIMARY KEY,partner_id bigint NOT NULL REFERENCES partners(id),partner_phone_id bigint NOT NULL REFERENCES partner_phones(id),amount bigint NOT NULL,cash_amount bigint NOT NULL DEFAULT 0,card_amount bigint NOT NULL DEFAULT 0,notes text,paid_at timestamptz NOT NULL DEFAULT now(),status record_status NOT NULL DEFAULT 'ACTIVE');
CREATE INDEX IF NOT EXISTS partner_payments_phone_idx ON partner_payments(partner_phone_id,paid_at);
CREATE TABLE IF NOT EXISTS returns (id bigserial PRIMARY KEY,product_id bigint NOT NULL REFERENCES products(id),inventory_unit_id bigint REFERENCES inventory_units(id),sale_id bigint REFERENCES sales(id),reason text NOT NULL,refunded_amount bigint NOT NULL DEFAULT 0,image_url text,processed_by bigint REFERENCES users(id),returned_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS returns_product_idx ON returns(product_id,returned_at);
CREATE TABLE IF NOT EXISTS receipts (id bigserial PRIMARY KEY,sale_id bigint NOT NULL UNIQUE REFERENCES sales(id),number varchar(50) NOT NULL UNIQUE,content text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS investments (id bigserial PRIMARY KEY,amount bigint NOT NULL,notes text,created_by bigint REFERENCES users(id),invested_at timestamptz NOT NULL DEFAULT now(),status record_status NOT NULL DEFAULT 'ACTIVE');
CREATE INDEX IF NOT EXISTS investments_status_date_idx ON investments(status,invested_at);
CREATE TABLE IF NOT EXISTS settings (key varchar(100) PRIMARY KEY,value text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bot_states (telegram_id bigint PRIMARY KEY,step varchar(100) NOT NULL,data jsonb NOT NULL DEFAULT '{}'::jsonb,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS legacy_imports (id bigserial PRIMARY KEY,entity_type varchar(60) NOT NULL,legacy_id bigint NOT NULL,new_id bigint NOT NULL,imported_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS legacy_imports_entity_uidx ON legacy_imports(entity_type,legacy_id);
INSERT INTO partners(name) VALUES ('Ishonch'),('Texno City') ON CONFLICT(name) DO NOTHING;
