import { and, asc, desc, eq, ilike, or, sql } from "drizzle-orm";
import { getDb } from "@/db/client";
import { products } from "@/db/schema";
import { databaseUrl } from "@/db/url";

export type InventoryOptions={condition?:string;platform?:"ANDROID"|"IOS"|"FEATURE";sort?:"newest"|"price_asc"|"price_desc"|"stock_asc"|"stock_desc";lowStock?:boolean;page?:number;limit?:number};
export async function listInventoryPage(search = "", category?: "SMARTPHONE" | "FEATURE_PHONE",options:InventoryOptions={}) {
  const db = getDb();
  const stock=sql<number>`coalesce((select sum(pb.available_quantity) from purchase_batches pb where pb.product_id=${products.id}),0)`,term=`%${search}%`;
  const conditions=[sql`${stock}>0`,options.lowStock?sql`${stock}<=${Math.max(1,Number(process.env.LOW_STOCK_THRESHOLD||2))}`:undefined,search?or(ilike(products.brand,term),ilike(products.model,term),ilike(products.storage,term),ilike(products.color,term),sql`exists(select 1 from inventory_units iu where iu.product_id=${products.id} and (iu.imei1 ilike ${term} or iu.product_code ilike ${term}))`):undefined,category?eq(products.category,category):undefined,options.condition?eq(products.condition,options.condition):undefined,options.platform?eq(products.platform,options.platform):undefined].filter(Boolean);
  const limit=Math.min(50,Math.max(1,options.limit??20)),page=Math.max(1,options.page??1),where=and(...conditions),order=options.sort==="price_asc"?asc(products.salePrice):options.sort==="price_desc"?desc(products.salePrice):options.sort==="stock_asc"?asc(stock):options.sort==="stock_desc"?desc(stock):desc(products.updatedAt);
  const [items,countRows]=await Promise.all([db.select({ id: products.id, category: products.category, platform:products.platform, brand: products.brand, model: products.model, slug: products.slug, description:products.description,storage:products.storage,ram:products.ram,color:products.color,condition:products.condition,warrantyDays:products.warrantyDays,salePrice: products.salePrice, isPublished: products.isPublished, quantity:stock, imei: sql<string | null>`(select iu.imei1 from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, batteryHealth:sql<string|null>`(select iu.battery_health from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, faceId:sql<string|null>`(select iu.face_id from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, trueTone:sql<string|null>`(select iu.true_tone from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, icloud:sql<string|null>`(select iu.icloud from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, repair:sql<string|null>`(select iu.repair from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, technicalState:sql<string|null>`(select iu.technical_state from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, code: sql<string | null>`(select iu.product_code from inventory_units iu where iu.product_id=${products.id} and iu.status='AVAILABLE' limit 1)`, imageUrl:sql<string|null>`(select m.url from media m where m.product_id=${products.id} order by m.sort_order limit 1)`,purchasePrice:sql<number>`coalesce((select pb.unit_cost + pb.extra_unit_cost from purchase_batches pb where pb.product_id=${products.id} and pb.available_quantity>0 order by pb.received_at asc limit 1),0)`,supplierName:sql<string|null>`(select pb.supplier_name from purchase_batches pb where pb.product_id=${products.id} and pb.available_quantity>0 order by pb.received_at asc limit 1)`,supplierPhone:sql<string|null>`(select pb.supplier_phone from purchase_batches pb where pb.product_id=${products.id} and pb.available_quantity>0 order by pb.received_at asc limit 1)` }).from(products).where(where).orderBy(order).limit(limit).offset((page-1)*limit),db.select({total:sql<number>`count(*)`}).from(products).where(where)]);
  return {items,total:Number(countRows[0]?.total??0),page,limit};
}

export async function listInventory(search="",category?:"SMARTPHONE"|"FEATURE_PHONE"){return (await listInventoryPage(search,category,{limit:50})).items;}

export async function inventoryStats(){const db=getDb();const rows=await db.execute(sql`select p.category,p.brand,coalesce(p.condition,'Kiritilmagan') condition,sum(pb.available_quantity)::int quantity,sum(pb.available_quantity*(pb.unit_cost+pb.extra_unit_cost))::bigint value from purchase_batches pb join products p on p.id=pb.product_id where pb.available_quantity>0 group by p.category,p.brand,coalesce(p.condition,'Kiritilmagan')`),data=rows.rows as unknown as {category:"SMARTPHONE"|"FEATURE_PHONE";brand:string;condition:string;quantity:number;value:number}[];return {total:data.reduce((n,x)=>n+Number(x.quantity),0),value:data.reduce((n,x)=>n+Number(x.value),0),smartphones:data.filter(x=>x.category==="SMARTPHONE").reduce((n,x)=>n+Number(x.quantity),0),featurePhones:data.filter(x=>x.category==="FEATURE_PHONE").reduce((n,x)=>n+Number(x.quantity),0),brands:Object.values(data.reduce<Record<string,{name:string;quantity:number;value:number}>>((a,x)=>{const k=x.brand||"Boshqa";a[k]??={name:k,quantity:0,value:0};a[k].quantity+=Number(x.quantity);a[k].value+=Number(x.value);return a},{})).sort((a,b)=>b.quantity-a.quantity),conditions:Object.values(data.reduce<Record<string,{name:string;quantity:number}>>((a,x)=>{a[x.condition]??={name:x.condition,quantity:0};a[x.condition].quantity+=Number(x.quantity);return a},{}))};}

export async function listPublicProducts(category?: "SMARTPHONE" | "FEATURE_PHONE") {
  if(!databaseUrl()) return [];
  const db = getDb();
  return db.select({ id: products.id, slug: products.slug, category: products.category, brand: products.brand, model: products.model, description: products.description, storage: products.storage, ram: products.ram, color: products.color, condition: products.condition, price: products.salePrice, warrantyDays: products.warrantyDays, quantity: sql<number>`coalesce((select sum(pb.available_quantity) from purchase_batches pb where pb.product_id=${products.id}),0)`, imageUrl: sql<string | null>`(select m.url from media m where m.product_id=${products.id} order by m.sort_order limit 1)` })
    .from(products).where(and(eq(products.isPublished, true), category ? eq(products.category, category) : undefined, sql`coalesce((select sum(pb.available_quantity) from purchase_batches pb where pb.product_id=${products.id}),0)>0`)).orderBy(asc(products.brand), asc(products.model));
}

export async function getPublicProduct(slug:string){if(!databaseUrl())return undefined; const db=getDb(); const [product]=await db.select({id:products.id,slug:products.slug,category:products.category,brand:products.brand,model:products.model,description:products.description,storage:products.storage,ram:products.ram,color:products.color,condition:products.condition,price:products.salePrice,warrantyDays:products.warrantyDays,quantity:sql<number>`coalesce((select sum(pb.available_quantity) from purchase_batches pb where pb.product_id=${products.id}),0)`,imageUrl:sql<string|null>`(select m.url from media m where m.product_id=${products.id} order by m.sort_order limit 1)`}).from(products).where(and(eq(products.slug,slug),eq(products.isPublished,true))).limit(1); return product; }
