import {eq} from "drizzle-orm";import {getDb} from "@/db/client";import {botStates,users} from "@/db/schema";import {APP_URL} from "@/lib/constants";import {answerTelegramCallback,sendTelegramMessage} from "@/lib/telegram-api";
type TgUser={id:number;first_name?:string;last_name?:string;username?:string};type TgMessage={chat:{id:number};from?:TgUser;text?:string};type TgCallback={id:string;from:TgUser;data?:string;message?:{chat:{id:number}}};export type TelegramUpdate={message?:TgMessage;callback_query?:TgCallback};
const adminKeyboard={keyboard:[[{text:"📥 Telefon sotib olish"},{text:"📤 Telefon sotish"}],[{text:"📦 Ombor"},{text:"↩️ Telefonni qaytarish"}],[{text:"💳 Qarzdorlar"},{text:"🏢 Bo‘lib to‘lash"}],[{text:"💵 To‘lov qabul qilish"},{text:"💸 Xarajatlar"}],[{text:"💼 Investitsiya"},{text:"📊 Hisobot"}],[{text:"⚙️ Sozlamalar"}]],resize_keyboard:true};
const customerKeyboard={keyboard:[[{text:"👤 Mening ma’lumotlarim"},{text:"🧾 Mening xaridlarim"}],[{text:"💳 Mening qarzim"},{text:"🛡 Mening kafolatlarim"}],[{text:"📞 Do‘kon bilan bog‘lanish"}]],resize_keyboard:true};
const appButton=(path="/app")=>({inline_keyboard:[[{text:"📱 TelMax Mini App’ni ochish",web_app:{url:`${APP_URL}${path}`}}]]});
async function upsertUser(from:TgUser){const db=getDb();const ownerId=Number(process.env.TELMAX_OWNER_TELEGRAM_ID||0);const existing=await db.query.users.findFirst({where:eq(users.telegramId,from.id)});const role=from.id===ownerId?"OWNER" as const:existing?.role??"CUSTOMER" as const;const [user]=await db.insert(users).values({telegramId:from.id,firstName:from.first_name||"Telegram",lastName:from.last_name,username:from.username,role}).onConflictDoUpdate({target:users.telegramId,set:{firstName:from.first_name||"Telegram",lastName:from.last_name,username:from.username,updatedAt:new Date()}}).returning();return user;}
async function setState(telegramId:number,step:string,data:Record<string,unknown>={}){await getDb().insert(botStates).values({telegramId,step,data}).onConflictDoUpdate({target:botStates.telegramId,set:{step,data,updatedAt:new Date()}});}
export async function handleTelegramUpdate(update:TelegramUpdate){const message=update.message,callback=update.callback_query,from=message?.from??callback?.from,chatId=message?.chat.id??callback?.message?.chat.id;if(!from||!chatId)return;const user=await upsertUser(from);const isAdmin=user.role!=="CUSTOMER";if(callback){await answerTelegramCallback(callback.id);if(callback.data==="main_menu")await sendTelegramMessage(chatId,"Asosiy menyu",isAdmin?adminKeyboard:customerKeyboard);return;}const text=message?.text?.trim()||"";if(text==="/start"||text==="/menu"||text==="⬅️ Orqaga"){await setState(from.id,"IDLE");await sendTelegramMessage(chatId,isAdmin?"TelMax boshqaruv botiga xush kelibsiz.":"TelMax telefon do‘koniga xush kelibsiz.",isAdmin?adminKeyboard:customerKeyboard);await sendTelegramMessage(chatId,isAdmin?"Bot, Mini App va sayt bitta ombor bilan ishlaydi.":"Telefonlar katalogini Mini App orqali ko‘ring.",appButton());return;}
 const routes:Record<string,[string,string]>={"📥 Telefon sotib olish":["Telefon qabul qilish","/app/sotib-olish"],"📤 Telefon sotish":["Telefon sotish","/app/sotish"],"📦 Ombor":["Ombor holati","/app/ombor"],"↩️ Telefonni qaytarish":["Telefonni qaytarish","/app/qaytarish"],"💳 Qarzdorlar":["Qarzdorlar","/app/qarzdorlar"],"🏢 Bo‘lib to‘lash":["Hamkorlar va bo‘lib to‘lash","/app/bolib-tolash"],"💵 To‘lov qabul qilish":["To‘lov qabul qilish","/app/tolov"],"💸 Xarajatlar":["Xarajatlar","/app/xarajatlar"],"💼 Investitsiya":["Investitsiyalar","/app/investitsiya"],"📊 Hisobot":["Hisobotlar","/app/hisobot"],"⚙️ Sozlamalar":["Sozlamalar","/app/sozlamalar"],"👤 Mening ma’lumotlarim":["Mening ma’lumotlarim","/app/profil"],"🧾 Mening xaridlarim":["Mening xaridlarim","/app/xaridlarim"],"💳 Mening qarzim":["Mening qarzim","/app/qarzim"],"🛡 Mening kafolatlarim":["Mening kafolatlarim","/app/kafolatlarim"],"📞 Do‘kon bilan bog‘lanish":["TelMax bilan bog‘lanish","/aloqa"]};const route=routes[text];if(route){await sendTelegramMessage(chatId,`<b>${route[0]}</b>`,appButton(route[1]));return;}await sendTelegramMessage(chatId,"Kerakli bo‘limni menyudan tanlang.",isAdmin?adminKeyboard:customerKeyboard);}
