import {NextResponse} from "next/server";
import {z} from "zod";
import {getSession} from "@/lib/session";
import {addInstallmentPayment,addPartner,createInstallment,getInstallmentDashboard,getInstallmentDetail} from "@/services/installments";

export const runtime="nodejs";
export async function GET(request:Request){const session=await getSession();if(!session||session.role==="CUSTOMER")return NextResponse.json({error:"Ruxsat yo‘q"},{status:401});try{const id=Number(new URL(request.url).searchParams.get("id")||0);return NextResponse.json(id?await getInstallmentDetail(id):await getInstallmentDashboard())}catch(error){console.error(error);return NextResponse.json({error:"Bo‘lib to‘lash ma’lumotlarini yuklab bo‘lmadi"},{status:500})}}

const partnerSchema=z.object({action:z.literal("partner"),name:z.string().trim().min(2).max(120)});
const createSchema=z.object({action:z.literal("create"),partnerId:z.coerce.number().int().positive(),productId:z.coerce.number().int().positive(),givenAmount:z.coerce.number().int().positive(),initialPayment:z.coerce.number().int().min(0),dueDate:z.string().optional().default(""),customerName:z.string().trim().max(160).optional().default(""),customerPhone:z.string().trim().max(20).optional().default(""),warrantyDays:z.coerce.number().int().min(0).max(3650).optional().default(0),notes:z.string().trim().max(500).optional().default("")});
const paymentSchema=z.object({action:z.literal("payment"),id:z.coerce.number().int().positive(),amount:z.coerce.number().int().positive(),method:z.enum(["CASH","CARD","TRANSFER","OTHER"]),notes:z.string().trim().max(500).optional().default("")});
export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Ruxsat yo‘q"},{status:401});try{const raw=await request.json();const actor={id:session.userId,role:session.role};if(raw.action==="partner"){const data=partnerSchema.parse(raw);return NextResponse.json({ok:true,partner:await addPartner({...data,actor})})}if(raw.action==="create"){const data=createSchema.parse(raw);return NextResponse.json({ok:true,...await createInstallment({...data,actor})})}if(raw.action==="payment"){const data=paymentSchema.parse(raw);return NextResponse.json({ok:true,...await addInstallmentPayment({...data,actor})})}return NextResponse.json({error:"Amal topilmadi"},{status:400})}catch(error){console.error(error);const message=error instanceof z.ZodError?error.issues[0]?.message??"Ma’lumotlarni tekshiring":error instanceof Error?error.message:"Xatolik";return NextResponse.json({error:message},{status:400})}}
