import Link from "next/link";
import {getDashboardData} from "@/lib/dashboard";
import {formatMoney} from "@/lib/money";
import {getSession} from "@/lib/session";
import {can} from "@/lib/permissions";
import {BUSINESS_TIME_ZONE} from "@/lib/constants";
import {TmLogo} from "@/components/tm-logo";
import {BarChart3,Box,CalendarDays,ChevronRight,CircleDollarSign,PackagePlus,ShoppingBag,ShoppingCart} from "@/components/icons";
export const dynamic="force-dynamic";
function Change({current,previous}:{current:number;previous:number}){if(!previous)return <small>Kecha: {previous.toLocaleString("uz-UZ")}{current>0&&<b className="up"> Yangi</b>}</small>;const percent=Math.round((current-previous)/previous*100),up=percent>=0;return <small>Kecha: {previous.toLocaleString("uz-UZ")} <b className={up?"up":"down"}>{up?"↑":"↓"} {Math.abs(percent)}%</b></small>}
function PhoneImage({url,feature=false}:{url:string|null;feature?:boolean}){return url?<img src={url} alt=""/>:<span className="home-phone-fallback">{feature?"▦":"▯"}</span>}
export default async function Dashboard(){const [d,session]=await Promise.all([getDashboardData(),process.env.NODE_ENV==="development"?Promise.resolve({name:"Kamoliddin",role:"OWNER" as const}):getSession()]);const showReport=!!session&&can(session.role,"report:read"),seller=session?.role==="STAFF",now=new Date(),date=new Intl.DateTimeFormat("uz-UZ",{timeZone:BUSINESS_TIME_ZONE,day:"numeric",month:"long",year:"numeric"}).format(now),weekday=new Intl.DateTimeFormat("uz-UZ",{timeZone:BUSINESS_TIME_ZONE,weekday:"long"}).format(now);
 return <div className="home-dashboard page-pad">
  <header className="app-header"><div className="brand-row"><TmLogo/><div><strong>Tel<span>Max</span></strong><small>Telefon Do‘koni</small></div></div><button className="home-bell" aria-label="Bildirishnomalar">♧</button></header>
  <section className="welcome-card"><span className="welcome-icon"><BarChart3/></span><div><h1>Xush kelibsiz, <b>{session?.name||"foydalanuvchi"}</b>!</h1><p>{seller?"Sotuvchi ish paneli":"Bugungi savdo va ombor holati"}</p></div><aside><CalendarDays/><span><b>{date}</b><small>{weekday}</small></span></aside></section>
  {seller?<section className="seller-home-note"><strong>Sotuvchi rejimi</strong><span>Siz telefon qo‘shishingiz, sotishingiz va omborni ko‘rishingiz mumkin. Moliyaviy hisobotlar faqat boshqaruv uchun.</span></section>:<section><div className="section-title"><h2>Bugungi ko‘rsatkichlar</h2><Link href="/app/hisobot">Barchasi <ChevronRight/></Link></div><div className="home-stats"><article><i className="red"><ShoppingBag/></i><span>Sotuvlar</span><strong>{d.today.salesCount} ta</strong><Change current={d.today.salesCount} previous={d.yesterday.salesCount}/></article><article><i className="green"><CircleDollarSign/></i><span>Jami summa</span><strong>{formatMoney(d.today.revenue)}</strong><Change current={d.today.revenue} previous={d.yesterday.revenue}/></article>{showReport&&<article><i className="purple">↗</i><span>Bugun foyda</span><strong>{formatMoney(d.today.profit)}</strong><Change current={d.today.profit} previous={d.yesterday.profit}/></article>}{showReport&&<article><i className="orange">◔</i><span>Umumiy foyda</span><strong>{formatMoney(d.totalProfit)}</strong><small>Tarixiy gross profit</small></article>}</div></section>}
  <section><h2>Tezkor amallar</h2><div className="home-actions"><Link className="primary" href="/app/sotish?new=1"><i><ShoppingCart/></i><span><strong>Telefon sotish</strong><small>Ombordagi telefonni sotish</small></span><ChevronRight/></Link><Link href="/app/sotib-olish"><i><PackagePlus/></i><span><strong>Telefon qo‘shish</strong><small>Telefonni omborga kiritish</small></span><ChevronRight/></Link><Link href="/app/ombor"><i><Box/></i><span><strong>Ombor</strong><small>Ombordagi telefonlar</small></span><ChevronRight/></Link>{showReport&&<Link href="/app/hisobot"><i><BarChart3/></i><span><strong>Hisobot</strong><small>Savdo va foyda hisobotlari</small></span><ChevronRight/></Link>}</div></section>
  <section><div className="section-title"><h2>Kam qoldi</h2><Link href="/app/ombor?stock=low">Barchasi <ChevronRight/></Link></div><div className="home-list">{d.lowStock.length?d.lowStock.map(p=><Link href={`/app/ombor?product=${p.id}`} key={p.id}><PhoneImage url={p.imageUrl} feature={p.category==="FEATURE_PHONE"}/><span><strong>{p.brand} {p.model}</strong><small>{p.category==="FEATURE_PHONE"?["Tugmali",p.color].filter(Boolean).join(" • "):[p.storage,p.ram,p.color,p.platform].filter(Boolean).join(" • ")}</small><b>Omborda: {p.quantity} dona</b></span><em><strong>{formatMoney(p.salePrice)}</strong><small>⚠ Kam qoldi</small></em><ChevronRight/></Link>):<div className="home-empty"><b>✓ Ombordagi qoldiq yaxshi</b><span>Hozircha kam qolgan telefon yo‘q.</span></div>}</div></section>
  {!seller&&<section><div className="section-title"><h2>So‘nggi sotuvlar</h2><Link href="/app/tarix">Barchasi <ChevronRight/></Link></div><div className="home-list recent">{d.recent.length?d.recent.map(s=><Link href={`/app/tarix/${s.id}`} key={s.id}><PhoneImage url={s.imageUrl} feature={s.category==="FEATURE_PHONE"}/><span><strong>{s.brand} {s.model}</strong><small>{s.category==="FEATURE_PHONE"?"Tugmali":s.storage}{s.color?` • ${s.color}`:""}</small><small>{s.quantity} dona • {formatMoney(s.total)}</small></span><em><small>{new Intl.DateTimeFormat("uz-UZ",{timeZone:BUSINESS_TIME_ZONE,hour:"2-digit",minute:"2-digit"}).format(s.soldAt)}</small>{showReport&&<b>+{formatMoney(s.profit)}</b>}</em><ChevronRight/></Link>):<div className="home-empty"><b>Hozircha sotuv yo‘q</b><span>Birinchi sotuvni amalga oshiring.</span><Link href="/app/sotish?new=1">+ Yangi sotuv</Link></div>}</div></section>}
 </div>}
