import Link from "next/link"; import {getDashboardData} from "@/lib/dashboard"; import {formatMoney} from "@/lib/money"; import {TmLogo} from "@/components/tm-logo"; import {Box,ChevronRight,CircleDollarSign,PackagePlus,ShoppingBag,Smartphone} from "@/components/icons";
export const dynamic="force-dynamic";
export default async function Dashboard(){const d=await getDashboardData();const total=d.smartphones+d.featurePhones;return <div className="dashboard page-pad">
 <header className="app-header"><div className="brand-row"><TmLogo/><div><strong>Tel<span>Max</span></strong><small>Telefon Do‘koni</small></div></div><button className="avatar" aria-label="Profil">TM<i/></button></header>
 <section className="hero-card"><p>Bugungi savdo</p><h1>{formatMoney(d.revenue)}</h1><div className="hero-stats"><div><ShoppingBag/><span><b>{d.salesCount} ta</b> sotuv</span></div><div><CircleDollarSign/><span><b>+{formatMoney(d.profit)}</b> foyda</span></div></div></section>
 <section><div className="section-title"><h2>Telefonlar</h2><span>Jami ombor: <b>{total} ta</b></span></div><div className="category-grid"><Link href="/app/ombor?category=SMARTPHONE"><i><Smartphone/></i><span><strong>Sensorli</strong><small><b>{d.smartphones}</b> ta omborda</small></span><ChevronRight/></Link><Link href="/app/ombor?category=FEATURE_PHONE"><i><span className="feature-glyph">▦</span></i><span><strong>Tugmali</strong><small><b>{d.featurePhones}</b> ta omborda</small></span><ChevronRight/></Link></div></section>
 <section><h2>Tezkor amallar</h2><div className="quick-grid"><Link href="/app/sotib-olish"><i><PackagePlus/></i><span><strong>Telefon olish</strong><small>Omborga qo‘shish</small></span></Link><Link href="/app/sotish"><i><CircleDollarSign/></i><span><strong>Telefon sotish</strong><small>Sotuv qilish</small></span></Link><Link href="/app/ombor"><i><Box/></i><span><strong>Ombor</strong><small>Ombor holati</small></span></Link></div></section>
 <section><h2>Bugungi holat</h2><div className="today-grid"><article><ShoppingBag/><span>Savdo<strong>{d.salesCount} ta</strong></span></article><article><CircleDollarSign/><span>Sof foyda<strong>{formatMoney(d.profit)}</strong></span></article></div></section>
 <section><div className="section-title"><h2>So‘nggi sotuvlar</h2><Link href="/app/tarix">Barchasi ›</Link></div><div className="sales-list">{d.recent.length?d.recent.map(s=><Link href={`/app/tarix/${s.id}`} key={s.id}><span className="sale-icon">{s.category==="SMARTPHONE"?"▯":"▦"}</span><span><strong>{s.name.trim()}</strong><small>{s.category==="SMARTPHONE"?"Sensorli":"Tugmali"} • {s.quantity} dona</small></span><span className="sale-money"><b>{formatMoney(s.total)}</b><em>+{formatMoney(s.profit)}</em></span><ChevronRight/></Link>):<div className="empty"><ShoppingBag/><strong>Hali sotuv yo‘q</strong><span>Birinchi sotuv shu yerda ko‘rinadi.</span></div>}</div></section>
 </div>}
