import { bigint, bigserial, boolean, check, date, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const roleEnum = pgEnum("role", ["OWNER", "ADMIN", "STAFF", "CUSTOMER"]);
export const categoryEnum = pgEnum("phone_category", ["SMARTPHONE", "FEATURE_PHONE"]);
export const stockStatusEnum = pgEnum("stock_status", ["AVAILABLE", "RESERVED", "SOLD", "RETURNED", "DEFECTIVE", "ARCHIVED"]);
export const recordStatusEnum = pgEnum("record_status", ["ACTIVE", "VOIDED", "CANCELLED"]);
export const paymentMethodEnum = pgEnum("payment_method", ["CASH", "CARD", "MIXED"]);
export const platformEnum = pgEnum("phone_platform", ["ANDROID", "IOS", "FEATURE"]);
export const debtStatusEnum = pgEnum("debt_status", ["ACTIVE", "PAID", "CANCELLED"]);

const created = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };

export const users = pgTable("users", { id: bigserial("id", { mode: "number" }).primaryKey(), telegramId: bigint("telegram_id", { mode: "number" }).notNull(), firstName: varchar("first_name", { length: 120 }).notNull(), lastName: varchar("last_name", { length: 120 }), username: varchar("username", { length: 100 }), phone: varchar("phone", { length: 20 }), role: roleEnum("role").notNull().default("CUSTOMER"), active: boolean("active").notNull().default(true), ...created }, (t) => [uniqueIndex("users_telegram_id_uidx").on(t.telegramId), index("users_role_idx").on(t.role)]);

export const products = pgTable("products", { id: bigserial("id", { mode: "number" }).primaryKey(), category: categoryEnum("category").notNull(), platform: platformEnum("platform"), legacyCode: varchar("legacy_code", { length: 40 }), brand: varchar("brand", { length: 100 }).notNull().default(""), model: varchar("model", { length: 160 }).notNull(), slug: varchar("slug", { length: 220 }).notNull(), description: text("description"), storage: varchar("storage", { length: 50 }), ram: varchar("ram", { length: 50 }), color: varchar("color", { length: 80 }), condition: varchar("condition", { length: 50 }), salePrice: bigint("sale_price", { mode: "number" }).notNull(), warrantyDays: integer("warranty_days").notNull().default(0), isPublished: boolean("is_published").notNull().default(false), ...created }, (t) => [uniqueIndex("products_slug_uidx").on(t.slug), uniqueIndex("products_legacy_code_uidx").on(t.legacyCode), index("products_category_idx").on(t.category), index("products_published_idx").on(t.isPublished)]);

export const purchaseBatches = pgTable("purchase_batches", { id: bigserial("id", { mode: "number" }).primaryKey(), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), unitCost: bigint("unit_cost", { mode: "number" }).notNull(), extraUnitCost: bigint("extra_unit_cost", { mode: "number" }).notNull().default(0), initialQuantity: integer("initial_quantity").notNull(), availableQuantity: integer("available_quantity").notNull(), defectiveQuantity: integer("defective_quantity").notNull().default(0), supplierName: varchar("supplier_name", { length: 160 }), supplierPhone: varchar("supplier_phone", { length: 20 }), receivedBy: bigint("received_by", { mode: "number" }).references(() => users.id), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(), notes: text("notes"), ...created }, (t) => [index("purchase_batches_product_fifo_idx").on(t.productId, t.receivedAt), check("batch_quantities_nonnegative", sql`${t.initialQuantity} >= 0 AND ${t.availableQuantity} >= 0 AND ${t.defectiveQuantity} >= 0`)]);

export const inventoryUnits = pgTable("inventory_units", { id: bigserial("id", { mode: "number" }).primaryKey(), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), batchId: bigint("batch_id", { mode: "number" }).notNull().references(() => purchaseBatches.id), productCode: varchar("product_code", { length: 40 }).notNull(), imei1: varchar("imei1", { length: 15 }), imei2: varchar("imei2", { length: 15 }), uzimei: varchar("uzimei", { length: 60 }), uzimeiMethod: varchar("uzimei_method", { length: 120 }), batteryHealth: varchar("battery_health", { length: 30 }), faceId: varchar("face_id", { length: 30 }), trueTone: varchar("true_tone", { length: 30 }), icloud: varchar("icloud", { length: 30 }), repair: text("repair"), packageInfo: text("package_info"), technicalState: text("technical_state"), status: stockStatusEnum("status").notNull().default("AVAILABLE"), ...created }, (t) => [uniqueIndex("inventory_code_uidx").on(t.productCode), uniqueIndex("inventory_imei1_uidx").on(t.imei1), uniqueIndex("inventory_imei2_uidx").on(t.imei2), index("inventory_status_idx").on(t.status)]);

export const customers = pgTable("customers", { id: bigserial("id", { mode: "number" }).primaryKey(), userId: bigint("user_id", { mode: "number" }).references(() => users.id), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 20 }).notNull(), ...created }, (t) => [uniqueIndex("customers_phone_uidx").on(t.phone)]);

export const sales = pgTable("sales", { id: bigserial("id", { mode: "number" }).primaryKey(), number: varchar("number", { length: 40 }).notNull(), customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id), soldBy: bigint("sold_by", { mode: "number" }).notNull().references(() => users.id), subtotal: bigint("subtotal", { mode: "number" }).notNull(), paidAmount: bigint("paid_amount", { mode: "number" }).notNull(), cashAmount: bigint("cash_amount", { mode: "number" }).notNull().default(0), cardAmount: bigint("card_amount", { mode: "number" }).notNull().default(0), debtAmount: bigint("debt_amount", { mode: "number" }).notNull().default(0), debtDueDate: date("debt_due_date"), grossProfit: bigint("gross_profit", { mode: "number" }).notNull(), paymentMethod: paymentMethodEnum("payment_method").notNull(), warrantyDays: integer("warranty_days").notNull().default(0), warrantyExpiresAt: date("warranty_expires_at"), status: recordStatusEnum("status").notNull().default("ACTIVE"), soldAt: timestamp("sold_at", { withTimezone: true }).notNull().defaultNow(), notes: text("notes"), ...created }, (t) => [uniqueIndex("sales_number_uidx").on(t.number), index("sales_sold_at_idx").on(t.soldAt, t.status)]);

export const saleItems = pgTable("sale_items", { id: bigserial("id", { mode: "number" }).primaryKey(), saleId: bigint("sale_id", { mode: "number" }).notNull().references(() => sales.id), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), inventoryUnitId: bigint("inventory_unit_id", { mode: "number" }).references(() => inventoryUnits.id), batchId: bigint("batch_id", { mode: "number" }).notNull().references(() => purchaseBatches.id), quantity: integer("quantity").notNull(), unitSalePrice: bigint("unit_sale_price", { mode: "number" }).notNull(), unitCostSnapshot: bigint("unit_cost_snapshot", { mode: "number" }).notNull(), profitSnapshot: bigint("profit_snapshot", { mode: "number" }).notNull(), ...created }, (t) => [index("sale_items_sale_idx").on(t.saleId), check("sale_item_quantity_positive", sql`${t.quantity} > 0`)]);

export const expenses = pgTable("expenses", { id: bigserial("id", { mode: "number" }).primaryKey(), category: varchar("category", { length: 80 }).notNull(), amount: bigint("amount", { mode: "number" }).notNull(), paymentMethod: paymentMethodEnum("payment_method").notNull(), notes: text("notes"), createdBy: bigint("created_by", { mode: "number" }).notNull().references(() => users.id), expenseDate: date("expense_date").notNull(), status: recordStatusEnum("status").notNull().default("ACTIVE"), ...created }, (t) => [index("expenses_date_idx").on(t.expenseDate, t.status)]);

export const inventoryMovements = pgTable("inventory_movements", { id: bigserial("id", { mode: "number" }).primaryKey(), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), batchId: bigint("batch_id", { mode: "number" }).references(() => purchaseBatches.id), type: varchar("type", { length: 40 }).notNull(), quantity: integer("quantity").notNull(), referenceType: varchar("reference_type", { length: 40 }), referenceId: bigint("reference_id", { mode: "number" }), actorId: bigint("actor_id", { mode: "number" }).references(() => users.id), details: jsonb("details"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("inventory_movements_product_idx").on(t.productId, t.createdAt)]);

export const auditLogs = pgTable("audit_logs", { id: bigserial("id", { mode: "number" }).primaryKey(), actorId: bigint("actor_id", { mode: "number" }).references(() => users.id), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entity_type", { length: 60 }).notNull(), entityId: bigint("entity_id", { mode: "number" }), details: jsonb("details"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("audit_entity_idx").on(t.entityType, t.entityId), index("audit_created_idx").on(t.createdAt)]);

export const telegramUpdates = pgTable("telegram_updates", { updateId: bigint("update_id", { mode: "number" }).primaryKey(), status: varchar("status", { length: 20 }).notNull().default("PROCESSING"), processedAt: timestamp("processed_at", { withTimezone: true }), error: text("error"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });

export const media = pgTable("media", { id: bigserial("id", { mode: "number" }).primaryKey(), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), url: text("url").notNull(), alt: varchar("alt", { length: 180 }).notNull(), sortOrder: integer("sort_order").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("media_product_idx").on(t.productId, t.sortOrder)]);

export const debts = pgTable("debts", { id: bigserial("id", { mode: "number" }).primaryKey(), saleId: bigint("sale_id", { mode: "number" }).notNull().references(() => sales.id), totalAmount: bigint("total_amount", { mode: "number" }).notNull(), paidAmount: bigint("paid_amount", { mode: "number" }).notNull(), remainingAmount: bigint("remaining_amount", { mode: "number" }).notNull(), dueDate: date("due_date").notNull(), status: debtStatusEnum("status").notNull().default("ACTIVE"), ...created }, (t) => [uniqueIndex("debts_sale_uidx").on(t.saleId), index("debts_status_due_idx").on(t.status, t.dueDate)]);
export const debtPayments = pgTable("debt_payments", { id: bigserial("id", { mode: "number" }).primaryKey(), debtId: bigint("debt_id", { mode: "number" }).notNull().references(() => debts.id), amount: bigint("amount", { mode: "number" }).notNull(), cashAmount: bigint("cash_amount", { mode: "number" }).notNull().default(0), cardAmount: bigint("card_amount", { mode: "number" }).notNull().default(0), notes: text("notes"), receivedBy: bigint("received_by", { mode: "number" }).references(() => users.id), paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(), status: recordStatusEnum("status").notNull().default("ACTIVE") }, (t) => [index("debt_payments_debt_idx").on(t.debtId, t.paidAt)]);
export const partners = pgTable("partners", { id: bigserial("id", { mode: "number" }).primaryKey(), name: varchar("name", { length: 120 }).notNull(), active: boolean("active").notNull().default(true), ...created }, (t) => [uniqueIndex("partners_name_uidx").on(t.name)]);
export const partnerPhones = pgTable("partner_phones", { id: bigserial("id", { mode: "number" }).primaryKey(), partnerId: bigint("partner_id", { mode: "number" }).notNull().references(() => partners.id), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), givenAmount: bigint("given_amount", { mode: "number" }).notNull(), receivedAmount: bigint("received_amount", { mode: "number" }).notNull().default(0), remainingAmount: bigint("remaining_amount", { mode: "number" }).notNull(), dueDate: date("due_date"), customerName: varchar("customer_name", { length: 160 }), customerPhone: varchar("customer_phone", { length: 20 }), warrantyDays: integer("warranty_days").notNull().default(0), notes: text("notes"), status: varchar("status", { length: 30 }).notNull().default("ACTIVE"), ...created }, (t) => [index("partner_phones_partner_idx").on(t.partnerId, t.status)]);
export const partnerPayments = pgTable("partner_payments", { id: bigserial("id", { mode: "number" }).primaryKey(), partnerId: bigint("partner_id", { mode: "number" }).notNull().references(() => partners.id), partnerPhoneId: bigint("partner_phone_id", { mode: "number" }).notNull().references(() => partnerPhones.id), amount: bigint("amount", { mode: "number" }).notNull(), cashAmount: bigint("cash_amount", { mode: "number" }).notNull().default(0), cardAmount: bigint("card_amount", { mode: "number" }).notNull().default(0), notes: text("notes"), paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(), status: recordStatusEnum("status").notNull().default("ACTIVE") }, (t) => [index("partner_payments_phone_idx").on(t.partnerPhoneId, t.paidAt)]);
export const returns = pgTable("returns", { id: bigserial("id", { mode: "number" }).primaryKey(), productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id), inventoryUnitId: bigint("inventory_unit_id", { mode: "number" }).references(() => inventoryUnits.id), saleId: bigint("sale_id", { mode: "number" }).references(() => sales.id), reason: text("reason").notNull(), refundedAmount: bigint("refunded_amount", { mode: "number" }).notNull().default(0), imageUrl: text("image_url"), processedBy: bigint("processed_by", { mode: "number" }).references(() => users.id), returnedAt: timestamp("returned_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("returns_product_idx").on(t.productId, t.returnedAt)]);
export const receipts = pgTable("receipts", { id: bigserial("id", { mode: "number" }).primaryKey(), saleId: bigint("sale_id", { mode: "number" }).notNull().references(() => sales.id), number: varchar("number", { length: 50 }).notNull(), content: text("content").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("receipts_sale_uidx").on(t.saleId), uniqueIndex("receipts_number_uidx").on(t.number)]);
export const investments = pgTable("investments", { id: bigserial("id", { mode: "number" }).primaryKey(), amount: bigint("amount", { mode: "number" }).notNull(), notes: text("notes"), createdBy: bigint("created_by", { mode: "number" }).references(() => users.id), investedAt: timestamp("invested_at", { withTimezone: true }).notNull().defaultNow(), status: recordStatusEnum("status").notNull().default("ACTIVE") }, (t) => [index("investments_status_date_idx").on(t.status, t.investedAt)]);
export const settings = pgTable("settings", { key: varchar("key", { length: 100 }).primaryKey(), value: text("value").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const botStates = pgTable("bot_states", { telegramId: bigint("telegram_id", { mode: "number" }).primaryKey(), step: varchar("step", { length: 100 }).notNull(), data: jsonb("data").notNull().default({}), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const legacyImports = pgTable("legacy_imports", { id: bigserial("id", { mode: "number" }).primaryKey(), entityType: varchar("entity_type", { length: 60 }).notNull(), legacyId: bigint("legacy_id", { mode: "number" }).notNull(), newId: bigint("new_id", { mode: "number" }).notNull(), importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("legacy_imports_entity_uidx").on(t.entityType, t.legacyId)]);
