"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {formatMoney} from "@/lib/money";

type Partner={id:number;name:string;active:boolean;phones:number;activePhones:number;given:number;received:number;remaining:number;overdue:number};
type Item={id:number;partnerId:number;partner:string;productId:number;brand:string;model:string;storage:string|null;color:string|null;category:"SMARTPHONE"|"FEATURE_PHONE";givenAmount:number;receivedAmount:number;remainingAmount:number;dueDate:string|null;customerName:string|null;customerPhone:string|null;status:string;imageUrl:string|null};
type InventoryItem={id:number;brand:string;model:string;storage:string|null;color:string|null;category:"SMARTPHONE"|"FEATURE_PHONE";quantity:number;imageUrl:string|null;salePrice:number};
type Data={summary:{given:number;received:number;remaining:number;active:number;overdueAmount:number};partners:Partner[];items:Item[]};
const empty:Data={summary:{given:0,received:0,remaining:0,active:0,overdueAmount:0},partners:[],items:[]};

export function InstallmentDashboard(){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[showPartner,setShowPartner]=useState(false),[showCreate,setShowCreate]=useState(false),[partnerName,setPartnerName]=useState(""),[inventory,setInventory]=useState<InventoryItem[]>([]),[selectedProduct,setSelectedProduct]=useState<number>(0),[selectedPartner,setSelectedPartner]=useState<number>(0),[given,setGiven]=useState(0),[initial,setInitial]=useState(0),[dueDate,setDueDate]=useState(""),[customerName,setCustomerName]=useState(""),[customerPhone,setCustomerPhone]=useState(""),[notes,setNotes]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch("/api/installments",{cache:"no-store"}),j=await r.json();if(r.ok)setData(j);else setMessage(j.error||"Yuklab bo‘lmadi");setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!showCreate)return;fetch("/api/inventory?category=SMARTPHONE",{cache:"no-store"}).then(r=>r.json()).then(j=>setInventory((j.items||[]).filter((x:InventoryItem)=>x.quantity>0))).catch(()=>setInventory([]))},[showCreate]);
 const filtered=useMemo(()=>data.items.filter(x=>{const text=`${x.partner} ${x.brand} ${x.model} ${x.customerName||""} ${x.customerPhone||""}`.toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;const overdue=x.status==="ACTIVE"&&x.dueDate&&new Date(x.dueDate+"T23:59:59").getTime()<Date.now();if(filter==="ACTIVE"&&x.status!=="ACTIVE")return false;if(filter==="OVERDUE"&&!overdue)return false;if(filter==="PAID"&&x.status!=="PAID")return false;return true}),[data.items,query,filter]);
 async function addNewPartner(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);const r=await fetch("/api/installments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"partner",name:partnerName})}),j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.error);setPartnerName("");setShowPartner(false);setMessage("Hamkor qo‘shildi");load()}
 async function create(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);const r=await fetch("/api/installments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",partnerId:selectedPartner,productId:selectedProduct,givenAmount:given,initialPayment:initial,dueDate,customerName,customerPhone,notes})}),j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.error);setShowCreate(false);setSelectedProduct(0);setSelectedPartner(0);setGiven(0);setInitial(0);setDueDate("");setCustomerName("");setCustomerPhone("");setNotes("");setMessage("Bo‘lib to‘lash yaratildi");load()}
 return <main className="installment-page">
  <header className="installment-head"><div><small>TelMax • Hamkorlar</small><h1>Bo‘lib to‘lash</h1></div><div className="installment-actions"><button onClick={()=>setShowPartner(true)}>+ Yangi hamkor</button><button className="primary" onClick={()=>setShowCreate(true)}>+ Yangi bo‘lib to‘lash</button></div></header>
  {message&&<div className="installment-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
  <section className="installment-kpis"><article><span>Jami berilgan</span><strong>{formatMoney(data.summary.given)}</strong></article><article><span>Qolgan summa</span><strong>{formatMoney(data.summary.remaining)}</strong></article><article><span>Muddati o‘tgan</span><strong className="danger">{formatMoney(data.summary.overdueAmount)}</strong></article><article><span>Faol telefonlar</span><strong>{data.summary.active} ta</strong></article></section>
  <section className="partner-strip"><div className="section-title"><h2>Hamkor do‘konlar</h2><span>{data.partners.length} ta</span></div><div className="partner-cards">{data.partners.map(p=><button key={p.id} onClick={()=>{setQuery(p.name);setFilter("ALL")}}><b>{p.name}</b><small>{p.activePhones} ta faol telefon</small><strong>{formatMoney(p.remaining)}</strong>{p.overdue>0&&<em>{p.overdue} ta kechikkan</em>}</button>)}{!data.partners.length&&!loading&&<div className="empty-card">Hali hamkor qo‘shilmagan</div>}</div></section>
  <section className="installment-list-section"><div className="section-title"><h2>Bo‘lib to‘lashlar</h2><span>{filtered.length} ta</span></div><div className="installment-search"><input placeholder="Hamkor, telefon yoki mijoz..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="installment-tabs">{[["ALL","Barchasi"],["ACTIVE","Faol"],["OVERDUE","Muddati o‘tgan"],["PAID","To‘langan"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div>
   <div className="installment-list">{loading?<div className="empty-card">Yuklanmoqda…</div>:filtered.length?filtered.map(x=>{const overdue=x.status==="ACTIVE"&&x.dueDate&&new Date(x.dueDate+"T23:59:59").getTime()<Date.now();return <Link href={`/app/bolib-tolash/${x.id}`} key={x.id} className="installment-card">{x.imageUrl?<img src={x.imageUrl} alt=""/>:<div className="phone-placeholder">▯</div>}<div><div className="installment-card-top"><b>{x.partner}</b><em className={x.status==="PAID"?"paid":overdue?"overdue":"active"}>{x.status==="PAID"?"To‘langan":overdue?"Kechikkan":"Faol"}</em></div><strong>{x.brand} {x.model}</strong><small>{[x.storage,x.color,x.customerName].filter(Boolean).join(" • ")}</small><span>Qoldiq <b>{formatMoney(x.remainingAmount)}</b></span><small>Muddat: {x.dueDate||"Belgilanmagan"}</small></div><i>›</i></Link>}):<div className="empty-card">Mos bo‘lib to‘lash topilmadi</div>}</div>
  </section>
  {showPartner&&<div className="installment-modal"><form onSubmit={addNewPartner}><button type="button" className="close" onClick={()=>setShowPartner(false)}>×</button><h2>Yangi hamkor</h2><p>Masalan: Ishonch, Alif yoki boshqa do‘kon.</p><label>Do‘kon nomi<input autoFocus value={partnerName} onChange={e=>setPartnerName(e.target.value)} placeholder="Ishonch" required/></label><button disabled={busy} className="primary-button wide">{busy?"Saqlanmoqda...":"Hamkorni saqlash"}</button></form></div>}
  {showCreate&&<div className="installment-modal scroll"><form onSubmit={create}><button type="button" className="close" onClick={()=>setShowCreate(false)}>×</button><h2>Yangi bo‘lib to‘lash</h2><p>Ombordagi telefonni hamkor do‘konga biriktiring.</p><label>Hamkor<select value={selectedPartner||""} onChange={e=>setSelectedPartner(Number(e.target.value))} required><option value="">Hamkorni tanlang</option>{data.partners.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Telefon<select value={selectedProduct||""} onChange={e=>{const id=Number(e.target.value);setSelectedProduct(id);const p=inventory.find(x=>x.id===id);if(p&&!given)setGiven(p.salePrice)}} required><option value="">Ombordan telefon tanlang</option>{inventory.map(x=><option key={x.id} value={x.id}>{x.brand} {x.model} — {x.quantity} dona</option>)}</select></label><label>Berilgan summa<input inputMode="numeric" value={given||""} onChange={e=>setGiven(Number(e.target.value.replace(/\D/g,"")))} required/></label><label>Boshlang‘ich to‘lov<input inputMode="numeric" value={initial||""} onChange={e=>setInitial(Number(e.target.value.replace(/\D/g,"")))}/></label><label>To‘lov muddati<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Mijoz ismi (ixtiyoriy)<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Azizbek"/></label><label>Telefon raqami (ixtiyoriy)<input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} placeholder="+998..."/></label><label>Izoh<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Qo‘shimcha ma’lumot"/></label><button disabled={busy||!selectedPartner||!selectedProduct} className="primary-button wide">{busy?"Saqlanmoqda...":"Bo‘lib to‘lashni saqlash"}</button></form></div>}
 </main>
}
