"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {Box,Search} from "./icons";
import {formatMoney} from "@/lib/money";

type Category="SMARTPHONE"|"FEATURE_PHONE";type Platform="ANDROID"|"IOS"|"FEATURE";type Sort="newest"|"price_asc"|"price_desc"|"stock_asc"|"stock_desc";
type Item={id:number;category:Category;platform:Platform|null;brand:string;model:string;description:string|null;storage:string|null;ram:string|null;color:string|null;condition:string|null;warrantyDays:number;salePrice:number;purchasePrice:number;quantity:number;imei:string|null;code:string|null;imageUrl:string|null;isPublished:boolean;batteryHealth:string|null;faceId:string|null;trueTone:string|null;icloud:string|null;repair:string|null;technicalState:string|null;supplierName:string|null;supplierPhone:string|null};
type Stats={total:number;value:number;smartphones:number;featurePhones:number;brands:{name:string;quantity:number;value:number}[];conditions:{name:string;quantity:number}[]};
const emptyStats:Stats={total:0,value:0,smartphones:0,featurePhones:0,brands:[],conditions:[]};
function technical(item:Item){try{return JSON.parse(item.technicalState||"{}") as {screen?:string;battery?:string}}catch{return {}}}
function ImageBox({item}:{item:Item}){return item.imageUrl?<img className="inventory-thumb" src={item.imageUrl} alt=""/>:<div className="inventory-placeholder">{item.category==="SMARTPHONE"?"▯":"▦"}</div>}

export function InventoryManager(){
 const routeParams=useSearchParams(),lowOnly=routeParams.get("stock")==="low",initialProduct=routeParams.get("product");
 const [items,setItems]=useState<Item[]>([]),[stats,setStats]=useState<Stats>(emptyStats),[q,setQ]=useState(""),[category,setCategory]=useState<""|Category>(""),[condition,setCondition]=useState(""),[platform,setPlatform]=useState<""|Platform>(""),[sort,setSort]=useState<Sort>("newest"),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[screen,setScreen]=useState<"list"|"filter"|"detail"|"edit"|"stats">("list"),[selected,setSelected]=useState<Item|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[newImage,setNewImage]=useState<File|null>(null),[preview,setPreview]=useState("");
 const picker=useRef<HTMLInputElement>(null);
 const load=useCallback(async(reset=true)=>{setLoading(true);const target=reset?1:page;const params=new URLSearchParams({q,page:String(target),sort});if(category)params.set("category",category);if(condition)params.set("condition",condition);if(platform)params.set("platform",platform);if(lowOnly)params.set("stock","low");const r=await fetch(`/api/inventory?${params}`,{cache:"no-store"}),d=await r.json();if(r.ok){setItems(old=>reset?d.items:[...old,...d.items]);setStats(d.stats??emptyStats);setTotal(d.total??0);if(reset)setPage(1)}setLoading(false)},[q,category,condition,platform,sort,page,lowOnly]);
 useEffect(()=>{const t=setTimeout(()=>load(true),220);return()=>clearTimeout(t)},[q,category,condition,platform,sort]);
 const open=(item:Item)=>{setSelected(item);setScreen("detail");setMessage("")};
 useEffect(()=>{if(initialProduct&&!selected){const item=items.find(x=>String(x.id)===initialProduct);if(item)open(item)}},[initialProduct,items,selected]);
 const clearFilters=()=>{setCategory("");setCondition("");setPlatform("");setSort("newest")};
 async function more(){const next=page+1;setPage(next);setLoading(true);const p=new URLSearchParams({q,page:String(next),sort});if(category)p.set("category",category);if(condition)p.set("condition",condition);if(platform)p.set("platform",platform);if(lowOnly)p.set("stock","low");const r=await fetch(`/api/inventory?${p}`),d=await r.json();if(r.ok)setItems(old=>[...old,...d.items]);setLoading(false)}
 function chooseImage(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]??null;if(file&&!["image/jpeg","image/png","image/webp"].includes(file.type))return setMessage("JPEG, PNG yoki WebP rasm tanlang");setNewImage(file);if(preview)URL.revokeObjectURL(preview);setPreview(file?URL.createObjectURL(file):"")}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||busy)return;setBusy(true);setMessage("");try{let imageUrl=selected.imageUrl;if(newImage){const fd=new FormData();fd.append("file",newImage);const up=await fetch("/api/uploads/phone-image",{method:"POST",body:fd}),ud=await up.json();if(!up.ok)throw new Error(ud.error);imageUrl=ud.url}const f=new FormData(e.currentTarget),body={id:selected.id,brand:String(f.get("brand")||""),model:String(f.get("model")||""),description:String(f.get("description")||""),storage:String(f.get("storage")||""),ram:String(f.get("ram")||""),color:String(f.get("color")||""),condition:String(f.get("condition")||""),salePrice:Number(f.get("salePrice")),purchasePrice:Number(f.get("purchasePrice")),quantity:Number(f.get("quantity")),adjustmentReason:String(f.get("adjustmentReason")||""),imageUrl,warrantyDays:Number(f.get("warrantyDays")),isPublished:f.get("isPublished")==="on"};const r=await fetch("/api/inventory",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("✓ O‘zgarishlar saqlandi");setNewImage(null);setPreview("");await load(true);setScreen("list")}catch(e){setMessage(e instanceof Error?e.message:"Saqlashda xato")}finally{setBusy(false)}}
 const header=(title:string)=><header className="inventory-mobile-header"><button onClick={()=>screen==="list"?history.back():setScreen("list")}>‹</button><h1>{title}</h1>{screen==="list"?<button onClick={()=>setScreen("filter")}>⌁</button>:<span/>}</header>;
 if(screen==="filter")return <section className="inventory-screen">{header("Filtr")}<button className="filter-clear" onClick={clearFilters}>Tozalash</button><FilterGroup title="Telefon turi" value={category} set={v=>setCategory(v as ""|Category)} options={[["","Barchasi"],["SMARTPHONE","Sensorli telefonlar"],["FEATURE_PHONE","Tugmali telefonlar"]]}/><FilterGroup title="Holati" value={condition} set={setCondition} options={[["","Barchasi"],["Yangi","Yangi"],["Ishlatilgan","Ishlatilgan"]]}/>{category!=="FEATURE_PHONE"&&<FilterGroup title="Platforma" value={platform} set={v=>setPlatform(v as ""|Platform)} options={[["","Barchasi"],["IOS","iOS"],["ANDROID","Android"]]}/>}<FilterGroup title="Saralash" value={sort} set={v=>setSort(v as Sort)} options={[["newest","Eng yangi"],["price_asc","Narxi: Arzon → Qimmat"],["price_desc","Narxi: Qimmat → Arzon"],["stock_asc","Omborda kamligi"],["stock_desc","Omborda ko‘pligi"]]}/><button className="primary-button wide" onClick={()=>setScreen("list")}>Qo‘llash</button></section>;
 if(screen==="stats")return <section className="inventory-screen">{header("Ombor statistikasi")}<StatsCards stats={stats}/><h2>Brendlar bo‘yicha</h2><div className="brand-stats">{stats.brands.map(b=><div key={b.name}><span><b>{b.name}</b><small>{b.quantity} dona • {formatMoney(b.value)}</small></span><i style={{width:`${stats.total?b.quantity/stats.total*100:0}%`}}/></div>)}</div><h2>Holati bo‘yicha</h2><div className="condition-stats">{stats.conditions.map(c=><article key={c.name}><b>{c.name}</b><strong>{c.quantity} dona</strong><small>{stats.total?Math.round(c.quantity/stats.total*100):0}%</small></article>)}</div></section>;
 if((screen==="detail"||screen==="edit")&&selected){const tech=technical(selected);if(screen==="edit")return <section className="inventory-screen">{header("Telefonni tahrirlash")}{message&&<p className="form-message error">{message}</p>}<form className="inventory-mobile-edit" onSubmit={save}><div className="edit-image"><ImageBox item={{...selected,imageUrl:preview||selected.imageUrl}}/><input ref={picker} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage}/><button type="button" onClick={()=>picker.current?.click()}>Rasmni o‘zgartirish</button></div><div className="form-grid"><label>Brend<input name="brand" defaultValue={selected.brand}/></label><label>Model *<input name="model" defaultValue={selected.model} required/></label><label>Holati<input name="condition" defaultValue={selected.condition||""}/></label><label>Rang<input name="color" defaultValue={selected.color||""}/></label>{selected.category==="SMARTPHONE"&&<label>Xotira<input name="storage" defaultValue={selected.storage||""}/></label>}{selected.platform==="ANDROID"&&<label>RAM<input name="ram" defaultValue={selected.ram||""}/></label>}<label>Olingan narx *<input name="purchasePrice" type="number" min="1" defaultValue={selected.purchasePrice}/></label><label>Sotish narxi *<input name="salePrice" type="number" min="1" defaultValue={selected.salePrice}/></label><label>Omborda soni *<input name="quantity" type="number" min="1" defaultValue={selected.quantity} readOnly={selected.category==="SMARTPHONE"}/></label>{selected.category==="FEATURE_PHONE"&&<label>O‘zgarish sababi<input name="adjustmentReason" placeholder="Inventarizatsiya"/></label>}<label>Kafolat (kun)<input name="warrantyDays" type="number" min="0" defaultValue={selected.warrantyDays}/></label><label className="full">Tavsif<textarea name="description" defaultValue={selected.description||""}/></label><label className="switch-label"><span>Saytda ko‘rsatish</span><input name="isPublished" type="checkbox" defaultChecked={selected.isPublished}/></label></div><button disabled={busy} className="primary-button wide">{busy?"Saqlanmoqda...":"Saqlash"}</button></form></section>;
 return <section className="inventory-screen">{header("Telefon tafsilotlari")}<div className="inventory-detail"><ImageBox item={selected}/><h2>{selected.brand} {selected.model}</h2><div className="detail-badges"><b>{selected.category==="SMARTPHONE"?"Sensorli":"Tugmali"}</b>{selected.condition&&<b>{selected.condition}</b>}</div><Detail label="Xotira" value={selected.category==="SMARTPHONE"?selected.storage:null}/><Detail label="RAM" value={selected.platform==="ANDROID"?selected.ram:null}/><Detail label="Rang" value={selected.color}/><Detail label="IMEI" value={selected.category==="SMARTPHONE"?selected.imei:null}/><Detail label="Battery Health" value={selected.platform==="IOS"&&selected.batteryHealth?`${selected.batteryHealth}%`:null}/><Detail label="iCloud" value={selected.platform==="IOS"?selected.icloud:null}/><Detail label="Face ID" value={selected.platform==="IOS"?selected.faceId:null}/><Detail label="True Tone" value={selected.platform==="IOS"?selected.trueTone:null}/><Detail label="Ekran" value={tech.screen}/><Detail label="Batareya" value={tech.battery}/><Detail label="Ta’mir holati" value={selected.repair}/><div className="detail-prices"><article><span>Olingan narx</span><b>{formatMoney(selected.purchasePrice)}</b></article><article><span>Sotish narxi</span><b>{formatMoney(selected.salePrice)}</b></article></div><div className="detail-stock">Omborda <b>{selected.quantity} dona</b></div>{(selected.supplierName||selected.supplierPhone)&&<div className="purchase-source"><h3>Xarid ma’lumotlari</h3>{selected.supplierName&&<p>Kimdan olindi: <b>{selected.supplierName}</b></p>}{selected.supplierPhone&&<p>Telefon: <b>{selected.supplierPhone}</b></p>}</div>}<div className="detail-actions"><Link href={`/app/sotish?product=${selected.id}`}>Sotish</Link><button onClick={()=>setScreen("edit")}>Tahrirlash</button></div></div></section>}
 return <section className="inventory-screen">{header("Ombor")}{message&&<p className="form-message success">{message}</p>}<button className="stats-link" onClick={()=>setScreen("stats")}><StatsCards stats={stats}/></button><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nomi, model, IMEI..."/></div><div className="filter-chips inventory-chips">{[["",`Barchasi (${stats.total})`],["SMARTPHONE",`Sensorli (${stats.smartphones})`],["FEATURE_PHONE",`Tugmali (${stats.featurePhones})`]].map(([v,l])=><button key={v} className={category===v?"active":""} onClick={()=>setCategory(v as ""|Category)}>{l}</button>)}</div>{loading&&!items.length?<div className="empty">Yuklanmoqda...</div>:items.length?<><div className="inventory-mobile-list">{items.map(item=><button key={item.id} onClick={()=>open(item)}><ImageBox item={item}/><span><strong>{item.brand} {item.model}</strong><small>{item.category==="FEATURE_PHONE"?["Tugmali",item.color].filter(Boolean).join(" • "):[item.storage,item.ram,item.color,item.platform].filter(Boolean).join(" • ")}</small><small className={item.quantity<=2?"low-stock":""}>{item.quantity<=2?`Kam qoldi: ${item.quantity} dona`:`Omborda: ${item.quantity} dona`}</small><b>{formatMoney(item.salePrice)}</b></span><em>›</em></button>)}</div>{items.length<total&&<button disabled={loading} className="load-more" onClick={more}>{loading?"Yuklanmoqda...":"Ko‘proq ko‘rsatish"}</button>}</>:<div className="empty large"><Box/><strong>{q||category||condition?"Telefon topilmadi":"Ombor hozircha bo‘sh"}</strong><span>{q||category||condition?"Qidiruvni tekshiring yoki filterlarni tozalang.":"Birinchi telefonni omborga qo‘shing."}</span>{(q||category||condition)&&<button onClick={()=>{setQ("");clearFilters()}}>Filterlarni tozalash</button>}</div>}<Link className="primary-button inventory-add" href="/app/sotib-olish">+ Telefon qo‘shish</Link></section>
}

function FilterGroup({title,value,set,options}:{title:string;value:string;set:(v:string)=>void;options:string[][]}){return <div className="filter-group"><h2>{title}</h2>{options.map(([v,l])=><button key={v} onClick={()=>set(v)}><span>{l}</span>{value===v&&<b>✓</b>}</button>)}</div>}
function StatsCards({stats}:{stats:Stats}){return <div className="inventory-stats"><article><span>Jami telefonlar</span><b>{stats.total} dona</b></article><article><span>Jami qiymat</span><b>{formatMoney(stats.value)}</b></article><article><span>Sensorli</span><b>{stats.smartphones} dona</b></article><article><span>Tugmali</span><b>{stats.featurePhones} dona</b></article></div>}
function Detail({label,value}:{label:string;value:string|null|undefined}){return value?<div className="detail-row"><span>{label}</span><b>{value}</b></div>:null}
