"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {formatMoney} from "@/lib/money";

type Period="today"|"7"|"30"|"month"|"custom";
const iso=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tashkent"}).format(d);
function dates(period:Period,customFrom?:string,customTo?:string){const now=new Date(),to=iso(now),from=new Date(now);if(period==="7")from.setDate(from.getDate()-6);else if(period==="30")from.setDate(from.getDate()-29);else if(period==="month")from.setDate(1);return {from:period==="custom"&&customFrom?customFrom:iso(from),to:period==="custom"&&customTo?customTo:to};}
const pct=(current:number,previous:number)=>previous===0?(current===0?0:null):(current-previous)*100/previous;
const percent=(v:number)=>`${Number.isFinite(v)?v.toFixed(1):"0.0"}%`;
const periodItems:[Period,string][]=[["today","Bugun"],["7","7 kun"],["30","30 kun"],["month","Shu oy"],["custom","Custom"]];
function PeriodTabs({value,onChange,compact=false}:{value:Period;onChange:(v:Period)=>void;compact?:boolean}){return <div className={`tm-period ${compact?"compact":""}`}>{periodItems.filter(([v])=>!compact||v!=="custom").map(([v,l])=><button key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{l}</button>)}</div>}
function Delta({current,previous}:{current:number;previous:number}){const p=pct(current,previous);if(p===null)return <small className="tm-delta neutral">Oldingi davr: 0</small>;return <small className={`tm-delta ${p>=0?"up":"down"}`}>{p>=0?"↑":"↓"} {Math.abs(p).toFixed(0)}%</small>}
function MiniLine({points}:{points:{revenue:number;profit:number}[]}){if(!points.length)return <div className="tm-empty">Tanlangan davrda savdo mavjud emas.</div>;const max=Math.max(1,...points.flatMap(p=>[p.revenue,p.profit])),w=320,h=150;const path=(key:"revenue"|"profit")=>points.map((p,i)=>`${i?"L":"M"}${(i/(Math.max(1,points.length-1)))*w},${h-(p[key]/max)*(h-15)-5}`).join(" ");return <svg className="tm-line-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Savdo va foyda dinamikasi"><path d={path("revenue")} className="sale"/><path d={path("profit")} className="profit"/></svg>}
function Donut({items,total}:{items:{percent:number}[];total:number}){let offset=0;const colors=["#f3262f","#4caf50","#ff7a00","#7c3aed","#0ea5e9","#eab308"];return <div className="tm-donut"><svg viewBox="0 0 42 42">{items.map((x,i)=>{const dash=`${Math.max(0,x.percent)} ${100-Math.max(0,x.percent)}`,node=<circle key={i} cx="21" cy="21" r="15.9155" fill="transparent" stroke={colors[i%colors.length]} strokeWidth="6" strokeDasharray={dash} strokeDashoffset={-offset} />;offset+=x.percent;return node})}</svg><div><strong>{total} ta</strong><span>Jami sotuv</span></div></div>}
function ReportHeader({title,back=false}:{title:string;back?:boolean}){return <div className="tm-report-head">{back?<Link href="/app/hisobot" className="tm-back">←</Link>:<img src="/brand/telmax-mark-tight.png" alt="TelMax"/>}<div>{!back&&<b>TelMax</b>}<span>{back?title:"Telefon Do‘koni"}</span></div>{!back&&<span className="tm-bell">◌</span>}</div>}
function ErrorBox({retry}:{retry:()=>void}){return <div className="tm-empty">Hisobotni yuklab bo‘lmadi.<button onClick={retry}>Qayta urinish</button></div>}
function Skeleton(){return <div className="tm-skeleton"><i/><i/><i/><i/><i/></div>}

export function MobileReport({mode="dashboard",saleId}:{mode?:"dashboard"|"brands"|"conditions"|"history"|"detail";saleId?:number}){
 const router=useRouter(),sp=useSearchParams();const [period,setPeriod]=useState<Period>((sp.get("period") as Period)||"today"),[customFrom,setCustomFrom]=useState(sp.get("from")||""),[customTo,setCustomTo]=useState(sp.get("to")||""),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[cancelOpen,setCancelOpen]=useState(false);
 const range=useMemo(()=>dates(period,customFrom,customTo),[period,customFrom,customTo]);
 const filters=useMemo(()=>({type:sp.get("type")||"",condition:sp.get("condition")||"",payment:sp.get("payment")||"",brand:sp.get("brand")||""}),[sp]);
 const load=useCallback(async()=>{setLoading(true);setError(false);const q=new URLSearchParams({view:mode==="conditions"?"conditions":mode,from:range.from,to:range.to});if(mode==="detail"&&saleId)q.set("id",String(saleId));for(const [k,v] of Object.entries(filters))if(v)q.set(k,v);try{const r=await fetch(`/api/reports?${q}`,{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(true)}finally{setLoading(false)}},[mode,range.from,range.to,saleId,filters]);useEffect(()=>{load()},[load]);
 const setAndUrl=(p:Period)=>{setPeriod(p);const q=new URLSearchParams(sp.toString());q.set("period",p);router.replace(`?${q}`,{scroll:false})};
 if(loading)return <div className="tm-report"><ReportHeader title="Hisobot" back={mode!=="dashboard"}/><Skeleton/></div>;if(error)return <div className="tm-report"><ReportHeader title="Hisobot" back={mode!=="dashboard"}/><ErrorBox retry={load}/></div>;
 if(mode==="detail"){const x=data?.item;if(!x)return <div className="tm-report"><ReportHeader title="Sotuv tafsilotlari" back/><div className="tm-empty">Savdo topilmadi.</div></div>;const item=x.items?.[0];const cancel=async()=>{const r=await fetch("/api/sale-cancellations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({saleId:x.id,reason:"Boshqa"})});if(r.ok){setCancelOpen(false);await load()}};return <div className="tm-report"><ReportHeader title="Sotuv tafsilotlari" back/><div className="tm-sale-hero">{item?.imageUrl?<img src={item.imageUrl}/>:<div className="tm-phone-placeholder">TM</div>}<div><em className={x.status==="CANCELLED"?"cancelled":"done"}>{x.status==="CANCELLED"?"Bekor qilingan":"Tugallangan"}</em><h2>{item?.brand} {item?.model}</h2><p>{[item?.storage,item?.color,item?.platform].filter(Boolean).join(" • ")}</p></div></div><div className="tm-detail-card">{[["Miqdor",`${item?.quantity||0} dona`],["Sotish narxi",formatMoney(item?.unitSalePrice||0)],["Jami summa",formatMoney(x.subtotal)],["Olingan narx",formatMoney((item?.unitCost||0)*(item?.quantity||0))],["Foyda",`+${formatMoney(x.grossProfit)}`],["To‘lov usuli",x.paymentMethod]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>{x.customerName||x.customerPhone?<section className="tm-info-section"><h3>Mijoz ma’lumotlari</h3>{x.customerName&&<div><span>Mijoz ismi</span><b>{x.customerName}</b></div>}{x.customerPhone&&<div><span>Telefon raqami</span><b>{x.customerPhone}</b></div>}</section>:null}<section className="tm-info-section"><h3>Sotuv ma’lumotlari</h3><div><span>Sotuvchi</span><b>{x.seller||"Admin"}</b></div><div><span>Sana va vaqt</span><b>{new Date(x.soldAt).toLocaleString("uz-UZ")}</b></div>{x.notes&&<div><span>Izoh</span><b>{x.notes}</b></div>}</section>{x.status==="ACTIVE"&&<button className="tm-cancel" onClick={()=>setCancelOpen(true)}>Sotuvni bekor qilish</button>}{cancelOpen&&<div className="tm-modal"><div><h3>Sotuvni bekor qilmoqchimisiz?</h3><p>Telefon omborga qaytariladi va hisobot qayta hisoblanadi.</p><button className="danger" onClick={cancel}>Bekor qilish</button><button onClick={()=>setCancelOpen(false)}>Orqaga</button></div></div>}</div>}
 return <div className="tm-report"><ReportHeader title={mode==="dashboard"?"Hisobot":mode==="brands"?"Brendlar bo‘yicha":mode==="conditions"?"Holati bo‘yicha":"Savdo tarixi"} back={mode!=="dashboard"}/>{mode==="dashboard"&&<h1>Hisobot</h1>}<PeriodTabs value={period} onChange={setAndUrl} compact={mode==="brands"||mode==="conditions"}/>{period==="custom"&&<div className="tm-custom"><input type="date" value={customFrom} max={iso(new Date())} onChange={e=>setCustomFrom(e.target.value)}/><input type="date" value={customTo} max={iso(new Date())} onChange={e=>setCustomTo(e.target.value)}/><button onClick={load}>Qo‘llash</button></div>}{mode==="dashboard"&&<Dashboard data={data}/>} {mode==="brands"&&<Breakdown data={data} kind="brand"/>}{mode==="conditions"&&<Conditions data={data}/>} {mode==="history"&&<History data={data} range={range} filters={filters}/>}</div>
}
function Dashboard({data}:{data:any}){const k=data.kpi,p=data.previous;return <><div className="tm-kpi-grid"><article><span>Jami savdo</span><strong>{formatMoney(k.revenue)}</strong><Delta current={k.revenue} previous={p.revenue}/></article><article><span>Jami foyda</span><strong>{formatMoney(k.profit)}</strong><Delta current={k.profit} previous={p.profit}/></article><article><span>Sotuvlar soni</span><strong>{k.count} ta</strong><Delta current={k.count} previous={p.count}/></article><article><span>O‘rtacha chek</span><strong>{formatMoney(k.average)}</strong></article></div><section className="tm-section"><h2>Savdo dinamikasi</h2><div className="tm-legend"><span className="red">● Savdo</span><span className="green">● Foyda</span></div><MiniLine points={data.trend}/></section><section className="tm-section"><div className="tm-section-title"><h2>Eng ko‘p sotilgan telefonlar</h2><Link href="/app/hisobot/tarix">Barchasi ›</Link></div>{data.top.length?data.top.map((x:any,i:number)=><div className="tm-top-row" key={x.productId}><b>#{i+1}</b>{x.imageUrl?<img src={x.imageUrl}/>:<div className="tm-mini-placeholder">TM</div>}<div><strong>{x.brand} {x.model}</strong><span>{[x.storage,x.color,x.platform].filter(Boolean).join(" • ")}</span><small>{x.quantity} ta</small></div><em>{formatMoney(x.revenue)}</em></div>):<div className="tm-empty">Hozircha sotuv yo‘q.</div>}</section><div className="tm-quick-links"><Link href="/app/hisobot/brendlar">Brendlar bo‘yicha <b>›</b></Link><Link href="/app/hisobot/holati">Holati bo‘yicha <b>›</b></Link><Link href="/app/hisobot/tarix">Savdo tarixi <b>›</b></Link></div></>}
function Breakdown({data}:{data:any;kind:string}){return <><Donut items={data.items} total={data.total}/><div className="tm-break-list">{data.items.map((x:any,i:number)=><div key={x.brand}><i style={{background:["#f3262f","#4caf50","#ff7a00","#7c3aed","#0ea5e9"][i%5]}}/><span><b>{x.brand}</b><small>{x.quantity} ta • {percent(x.percent)}</small></span><strong>{formatMoney(x.revenue)}</strong></div>)}</div></>}
function Conditions({data}:{data:any}){return <><Donut items={data.items} total={data.total}/><div className="tm-break-list">{data.items.map((x:any,i:number)=><div key={x.condition}><i style={{background:i?"#ff7a00":"#4caf50"}}/><span><b>{x.condition}</b><small>{x.quantity} ta • {percent(x.percent)}</small></span><strong>{formatMoney(x.revenue)}</strong></div>)}</div><section className="tm-margin-card"><span>Foyda marjasi</span><strong>{percent(data.margin)}</strong><small>Gross Profit / Revenue</small></section></>}
function History({data,range,filters}:{data:any;range:any;filters:any}){const items=data.items||[],sum=items.reduce((s:number,x:any)=>s+x.subtotal,0),profit=items.reduce((s:number,x:any)=>s+x.grossProfit,0);const params=new URLSearchParams({from:range.from,to:range.to,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}).toString();return <><Link className="tm-filter-link" href={`/app/hisobot/filter?${params}`}>Filter ⚙</Link><section className="tm-history-summary"><span>Jami</span><strong>{formatMoney(sum)}</strong><small>{items.length} ta sotuv <em>{formatMoney(profit)} foyda</em></small></section><div className="tm-history-list">{items.length?items.map((x:any)=><Link key={`${x.id}-${x.model}`} href={`/app/hisobot/tarix/${x.id}`}><time>{new Date(x.soldAt).toLocaleTimeString("uz-UZ",{hour:"2-digit",minute:"2-digit"})}</time>{x.imageUrl?<img src={x.imageUrl}/>:<div className="tm-mini-placeholder">TM</div>}<div><b>{x.brand} {x.model}</b><span>{[x.category==="FEATURE_PHONE"?"Tugmali":x.storage,x.color].filter(Boolean).join(" • ")}</span><small>{x.quantity} dona</small></div><em>+{formatMoney(x.grossProfit)}</em></Link>):<div className="tm-empty">Tanlangan davrda savdo mavjud emas.</div>}</div></>}
