"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {Search,ShoppingCart} from "./icons";
import {formatMoney} from "@/lib/money";

type Category="SMARTPHONE"|"FEATURE_PHONE";type Payment="CASH"|"CARD"|"TRANSFER"|"OTHER";
type Item={id:number;category:Category;platform:"ANDROID"|"IOS"|"FEATURE"|null;brand:string;model:string;salePrice:number;purchasePrice:number;quantity:number;storage:string|null;ram:string|null;color:string|null;condition:string|null;imei:string|null;imageUrl:string|null;batteryHealth:string|null;faceId:string|null;trueTone:string|null;repair:string|null;technicalState:string|null};
const paymentLabels:Record<Payment,string>={CASH:"Naqd pul",CARD:"Bank kartasi",TRANSFER:"Pul o‘tkazish",OTHER:"Boshqa"};
const quick=[1,2,5,10];
function maskImei(v:string|null){return v?`${"*".repeat(Math.max(0,v.length-4))}${v.slice(-4)}`:"Kiritilmagan"}
function stateOf(item:Item){try{return JSON.parse(item.technicalState||"{}") as {screen?:string;battery?:string}}catch{return {}}}

export function SaleForm({initialProduct}:{initialProduct?:string}){
 const [items,setItems]=useState<Item[]>([]),[category,setCategory]=useState<Category>("SMARTPHONE"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Item|null>(null),[step,setStep]=useState(0),[quantity,setQuantity]=useState(1),[price,setPrice]=useState(0),[payment,setPayment]=useState<Payment>("CASH"),[otherPayment,setOtherPayment]=useState(""),[customerName,setCustomerName]=useState(""),[customerPhone,setCustomerPhone]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<{remainingStock:number;grossProfit:number}|null>(null),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const load=useCallback(async()=>{const r=await fetch(`/api/inventory?q=${encodeURIComponent(query)}&category=${category}`,{cache:"no-store"}),d=await r.json();if(r.ok)setItems((d.items??[]).filter((x:Item)=>x.quantity>0));},[query,category]);
 useEffect(()=>{const timer=setTimeout(load,180);return()=>clearTimeout(timer)},[load]);
 useEffect(()=>{if(initialProduct&&!selected){const found=items.find(x=>String(x.id)===initialProduct);if(found)choose(found)}},[initialProduct,items,selected]);
 const total=price*quantity,technical=selected?stateOf(selected):{};
 const choose=(item:Item)=>{setSelected(item);setPrice(item.salePrice);setQuantity(1);setStep(1);setError("")};
 const reset=()=>{setSelected(null);setStep(0);setQuantity(1);setPrice(0);setCustomerName("");setCustomerPhone("");setNotes("");setPayment("CASH");setResult(null);setError("");setRequestKey(crypto.randomUUID());load()};
 const next=()=>{setError("");if(step===2&&(!price||quantity<1||!selected||quantity>selected.quantity))return setError("Narx va miqdorni tekshiring");setStep(v=>v+1)};
 async function submit(){if(!selected||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:selected.id,quantity,unitSalePrice:price,paymentMethod:payment,customerName,customerPhone,notes:payment==="OTHER"?[otherPayment,notes].filter(Boolean).join(" — "):notes,idempotencyKey:requestKey})}),d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d);setStep(5)}catch(e){setError(e instanceof Error?e.message:"Sotuvda xato")}finally{setBusy(false)}}
 if(step===5&&selected&&result)return <section className="sale-flow flow-card flow-success"><div className="success-check">✓</div>{selected.imageUrl&&<img src={selected.imageUrl} alt=""/>}<h2>Muvaffaqiyatli sotildi!</h2><strong>{selected.brand} {selected.model}</strong><p>{quantity} dona</p><dl><dt>Sotish narxi</dt><dd>{formatMoney(price)}</dd><dt>Jami</dt><dd className="red">{formatMoney(total)}</dd><dt>To‘lov</dt><dd>{paymentLabels[payment]}</dd>{customerName&&<><dt>Mijoz</dt><dd>{customerName}</dd></>}{customerPhone&&<><dt>Telefon</dt><dd>{customerPhone}</dd></>}</dl><button className="primary-button wide" onClick={reset}>Yangi sotuv qilish</button><Link className="flow-secondary" href="/app">Bosh sahifaga qaytish</Link></section>;
 return <section className="purchase-flow sale-flow"><header><button type="button" onClick={()=>step?setStep(step-1):history.back()}>‹</button><div><h2>{step?"Telefon sotish":"Telefon tanlash"}</h2><p>{step?`${step}/4 qadam`:"Ombordagi telefonlar"}</p></div></header>{step>0&&<div className="flow-progress"><span style={{width:`${Math.min(100,step/4*100)}%`}}/></div>}{error&&<p className="form-message error">{error}</p>}
 {step===0&&<div className="flow-section sale-select"><div className="sale-tabs"><button className={category==="SMARTPHONE"?"active":""} onClick={()=>setCategory("SMARTPHONE")}>Sensorli telefonlar</button><button className={category==="FEATURE_PHONE"?"active":""} onClick={()=>setCategory("FEATURE_PHONE")}>Tugmali telefonlar</button></div><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={category==="SMARTPHONE"?"Nom, brend, model yoki IMEI":"Telefon nomi yoki brend"}/></div><div className="sale-products">{items.map(item=><button key={item.id} onClick={()=>choose(item)}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<i>{item.category==="SMARTPHONE"?"▯":"▦"}</i>}<span><strong>{item.brand} {item.model}</strong><small>{[item.storage,item.color].filter(Boolean).join(" • ")}</small><small>Omborda: {item.quantity} dona</small><b>{formatMoney(item.salePrice)}</b></span><em>›</em></button>)}{!items.length&&<div className="empty large"><ShoppingCart/><strong>Sotiladigan telefon yo‘q</strong><span>Qidiruvni o‘zgartiring yoki omborga telefon qo‘shing.</span></div>}</div></div>}
 {step===1&&selected&&<div className="flow-section sale-review"><h1>Ma’lumotni tekshirish</h1><div className="sale-product-card">{selected.imageUrl&&<img src={selected.imageUrl} alt=""/>}<div><h2>{selected.brand} {selected.model}</h2><span className="platform-badge">{selected.platform}</span><p>{[selected.storage,selected.ram,selected.color].filter(Boolean).join(" • ")}</p><p>IMEI: {maskImei(selected.imei)}</p><b>Omborda: {selected.quantity} dona</b></div></div>{selected.condition&&<div className="condition-row"><span>Telefon holati</span><b>{selected.condition}</b></div>}{technical.screen&&<div className="condition-row"><span>Ekran</span><b>{technical.screen}</b></div>}{technical.battery&&<div className="condition-row"><span>Batareya</span><b>{technical.battery}</b></div>}{selected.repair&&<div className="condition-row"><span>Ta’mir holati</span><b>{selected.repair}</b></div>}<button className="primary-button wide" onClick={()=>setStep(2)}>Davom etish</button></div>}
 {step===2&&selected&&<div className="flow-section"><h1>Sotish narxi va miqdor</h1><div className="cost-card"><span>Olingan narx</span><b>{formatMoney(selected.purchasePrice)}</b></div><label>Sotish narxi *<input inputMode="numeric" value={price||""} onChange={e=>setPrice(Number(e.target.value.replace(/\D/g,"")))}/></label><div className="price-suggestions"><button type="button" onClick={()=>setPrice(Math.round(selected.purchasePrice*1.2))}><b>+20%</b><span>{formatMoney(Math.round(selected.purchasePrice*1.2))}</span></button><button type="button" onClick={()=>setPrice(Math.round(selected.purchasePrice*1.3))}><b>+30%</b><span>{formatMoney(Math.round(selected.purchasePrice*1.3))}</span></button></div><label>Miqdor *<div className="quantity"><button type="button" onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><input readOnly value={`${quantity} dona`}/><button type="button" onClick={()=>setQuantity(Math.min(selected.quantity,quantity+1))}>+</button></div><div className="flow-chips">{quick.filter(n=>n<=selected.quantity).map(n=><button type="button" className={quantity===n?"active":""} key={n} onClick={()=>setQuantity(n)}>{n} dona</button>)}</div></label><div className="sale-total"><span>Jami summa</span><strong>{formatMoney(total)}</strong></div><button className="primary-button wide" onClick={next}>Davom etish</button></div>}
 {step===3&&<div className="flow-section"><h1>To‘lov va mijoz</h1><div className="payment-grid">{(Object.keys(paymentLabels) as Payment[]).map(v=><button type="button" className={payment===v?"active":""} onClick={()=>setPayment(v)} key={v}>{paymentLabels[v]}</button>)}</div>{payment==="OTHER"&&<label>To‘lov turi<input value={otherPayment} onChange={e=>setOtherPayment(e.target.value)} placeholder="To‘lov usulini kiriting"/></label>}<h2 className="section-subtitle">Mijoz ma’lumotlari</h2><label>Mijoz ismi (ixtiyoriy)<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Azizbek"/></label><label>Telefon raqami (ixtiyoriy)<input type="tel" inputMode="tel" value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} placeholder="+998 90 123 45 67"/></label><label>Izoh (ixtiyoriy)<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} placeholder="Doimiy mijoz"/></label><button className="primary-button wide" onClick={()=>setStep(4)}>Tekshirish</button></div>}
 {step===4&&selected&&<div className="flow-section review"><h1>Yakuniy tekshirish</h1><div className="sale-product-card compact">{selected.imageUrl&&<img src={selected.imageUrl} alt=""/>}<div><h2>{selected.brand} {selected.model}</h2><p>{[selected.storage,selected.color].filter(Boolean).join(" • ")}</p><p>{quantity} dona</p></div></div><dl><dt>Dona narxi</dt><dd>{formatMoney(price)}</dd><dt>Jami summa</dt><dd className="red">{formatMoney(total)}</dd><dt>To‘lov</dt><dd>{paymentLabels[payment]}</dd>{customerName&&<><dt>Mijoz</dt><dd>{customerName}</dd></>}{customerPhone&&<><dt>Telefon</dt><dd>{customerPhone}</dd></>}{notes&&<><dt>Izoh</dt><dd>{notes}</dd></>}</dl><button disabled={busy} className="primary-button wide" onClick={submit}>{busy?"Sotilmoqda...":"Sotishni tasdiqlash"}</button></div>}
 </section>
}
