import fs from "node:fs";
import mysql from "mysql2/promise";
import {Pool} from "@neondatabase/serverless";
import {readMysqlDump} from "./mysql-dump-reader.mjs";
const php=fs.readFileSync(process.env.LEGACY_CONFIG_PATH||"F:/Telegram savdo boti v1.0/config.php","utf8"),block=php.match(/['\"]baza['\"]\s*=>\s*\[(.*?)\]/s)?.[1];if(!block)throw new Error("Eski baza sozlamasi topilmadi");
const val=k=>block.match(new RegExp(`[\"']${k}[\"']\\s*=>\\s*[\"']([^\"']*)[\"']`))?.[1];
const dumpPath=process.env.LEGACY_DUMP_PATH;const dump=dumpPath?readMysqlDump(dumpPath):null;const source=dump?null:await mysql.createConnection({host:val("host"),port:Number(val("port")||3306),user:val("user")||val("username"),password:val("password")||val("parol"),database:val("database")||val("name")||val("nomi"),charset:"utf8mb4"}),target=new Pool({connectionString:process.env.DATABASE_URL});
const rows=async t=>dump?dump.rows(t):(await source.query(`SELECT * FROM \`${t}\``))[0],one=async(q,a=[])=>(await target.query(q,a)).rows[0],mapped=async(t,id)=>(await one("select new_id from legacy_imports where entity_type=$1 and legacy_id=$2",[t,id]))?.new_id,mark=(t,o,n)=>target.query("insert into legacy_imports(entity_type,legacy_id,new_id) values($1,$2,$3) on conflict(entity_type,legacy_id) do nothing",[t,o,n]),rec=v=>v==="Bekor qilingan"?"CANCELLED":"ACTIVE";
try{const ownerTg=Number(process.env.TELMAX_OWNER_TELEGRAM_ID);let owner=await one("select id from users where telegram_id=$1",[ownerTg]);if(!owner)owner=await one("insert into users(telegram_id,first_name,role) values($1,'TelMax','OWNER') returning id",[ownerTg]);
for(const m of await rows("mijozlar")){if(await mapped("customer",m.id))continue;const u=await one("insert into users(telegram_id,first_name,username,phone,role) values($1,$2,$3,$4,'CUSTOMER') on conflict(telegram_id) do update set first_name=excluded.first_name,username=excluded.username,phone=excluded.phone returning id",[m.telegram_id,m.ism,m.username,m.telefon]),c=await one("insert into customers(user_id,name,phone,created_at) values($1,$2,$3,$4) on conflict(phone) do update set name=excluded.name,user_id=excluded.user_id returning id",[u.id,m.ism,m.telefon,m.royxat_sanasi]);await mark("customer",m.id,c.id)}
for(const t of await rows("telefonlar")){if(await mapped("product",t.id))continue;const cat=t.tur==="Tugmali"?"FEATURE_PHONE":"SMARTPHONE",platform=t.tur==="iOS"?"IOS":t.tur==="Android"?"ANDROID":"FEATURE",slug=`legacy-${String(t.mahsulot_kodi).toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${t.id}`,p=await one("insert into products(category,platform,legacy_code,brand,model,slug,storage,ram,color,condition,sale_price,warranty_days,is_published,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true,$13) returning id",[cat,platform,t.mahsulot_kodi,t.brend||"",t.model,slug,t.xotira,t.ram,t.rang,t.yangi_holati,Number(t.sotuv_narxi),Number(t.kafolat_kun||0),t.yaratilgan]),b=await one("insert into purchase_batches(product_id,unit_cost,extra_unit_cost,initial_quantity,available_quantity,defective_quantity,supplier_name,supplier_phone,received_by,received_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id",[p.id,Number(t.olish_narxi),Number(t.qoshimcha_xarajat||0),Number(t.dastlabki_miqdor||1),Number(t.mavjud_miqdor||0),Number(t.brak_miqdor||0),t.sotuvchi_ism,t.sotuvchi_telefon,owner.id,t.yaratilgan]);if(cat==="SMARTPHONE"){const st=t.holat==="Sotilgan"?"SOLD":t.holat==="Qaytgan"?"RETURNED":t.holat==="Bekor qilingan"?"ARCHIVED":"AVAILABLE";await target.query("insert into inventory_units(product_id,batch_id,product_code,imei1,imei2,uzimei,uzimei_method,battery_health,face_id,true_tone,icloud,repair,package_info,technical_state,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)",[p.id,b.id,t.mahsulot_kodi,t.imei1||null,t.imei2||null,t.uzimei,t.uzimei_usul,t.battery_health,t.face_id,t.true_tone,t.icloud,t.tamir,t.komplekt,t.telefon_holati,st,t.yaratilgan])}await mark("product",t.id,p.id);await mark("batch",t.id,b.id)}
for(const s of await rows("sotuvlar")){if(await mapped("sale",s.id))continue;const pid=await mapped("product",s.telefon_id),bid=await mapped("batch",s.telefon_id),cid=s.mijoz_id?await mapped("customer",s.mijoz_id):null;if(!pid||!bid)continue;const pay=Number(s.naqd)>0&&Number(s.karta)>0?"MIXED":Number(s.karta)>0?"CARD":"CASH",sale=await one("insert into sales(number,customer_id,sold_by,subtotal,paid_amount,cash_amount,card_amount,debt_amount,debt_due_date,gross_profit,payment_method,warranty_days,warranty_expires_at,status,sold_at,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning id",[`LEG-${s.id}`,cid,owner.id,Number(s.sotuv_narxi),Number(s.berilgan_summa),Number(s.naqd||0),Number(s.karta||0),Number(s.qolgan_qarz||0),s.qarz_muddati,Number(s.sotuv_narxi)-Number(s.miqdor||1)*Number(s.birlik_xarid_narxi||0),pay,Number(s.kafolat_kun||0),s.kafolat_tugashi,rec(s.holat),s.sana,s.izoh]),unit=await one("select id from inventory_units where product_id=$1 limit 1",[pid]);await target.query("insert into sale_items(sale_id,product_id,inventory_unit_id,batch_id,quantity,unit_sale_price,unit_cost_snapshot,profit_snapshot,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[sale.id,pid,unit?.id||null,bid,Number(s.miqdor||1),Number(s.birlik_sotuv_narxi||s.sotuv_narxi),Number(s.birlik_xarid_narxi||0),Number(s.sotuv_narxi)-Number(s.miqdor||1)*Number(s.birlik_xarid_narxi||0),s.sana]);await mark("sale",s.id,sale.id)}
for(const q of await rows("qarzlar")){if(await mapped("debt",q.id))continue;const sid=await mapped("sale",q.sotuv_id);if(!sid)continue;const d=await one("insert into debts(sale_id,total_amount,paid_amount,remaining_amount,due_date,status) values($1,$2,$3,$4,$5,$6) on conflict(sale_id) do update set remaining_amount=excluded.remaining_amount returning id",[sid,Number(q.umumiy_summa),Number(q.berilgan_summa),Number(q.qolgan_qarz),q.muddat,q.holat==="To‘liq to‘langan"?"PAID":q.holat==="Bekor qilingan"?"CANCELLED":"ACTIVE"]);await mark("debt",q.id,d.id)}
for(const p of await rows("qarz_tolovlari")){if(await mapped("debt_payment",p.id))continue;const did=await mapped("debt",p.qarz_id);if(!did)continue;const x=await one("insert into debt_payments(debt_id,amount,cash_amount,card_amount,notes,received_by,paid_at,status) values($1,$2,$3,$4,$5,$6,$7,$8) returning id",[did,Number(p.summa),Number(p.naqd||0),Number(p.karta||0),p.izoh,owner.id,p.sana,rec(p.holat)]);await mark("debt_payment",p.id,x.id)}
for(const i of await rows("investitsiyalar")){if(await mapped("investment",i.id))continue;const x=await one("insert into investments(amount,notes,created_by,invested_at,status) values($1,$2,$3,$4,$5) returning id",[Number(i.summa),i.izoh,owner.id,i.sana,rec(i.holat)]);await mark("investment",i.id,x.id)}
for(const x of await rows("xarajatlar")){if(await mapped("expense",x.id))continue;const e=await one("insert into expenses(category,amount,payment_method,notes,created_by,expense_date,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning id",[x.tur,Number(x.summa),x.tolov_usuli==="Karta"?"CARD":"CASH",x.izoh,owner.id,new Date(x.sana).toISOString().slice(0,10),rec(x.holat),x.sana]);await mark("expense",x.id,e.id)}
for(const h of await rows("hamkorlar")){if(await mapped("partner",h.id))continue;const p=await one("insert into partners(name,active) values($1,$2) on conflict(name) do update set active=excluded.active returning id",[h.nomi,Boolean(h.faol)]);await mark("partner",h.id,p.id)}
const summary={};for(const t of ["mijozlar","telefonlar","sotuvlar","qarzlar","qarz_tolovlari","investitsiyalar","xarajatlar","hamkorlar"])summary[t]=(await rows(t)).length;console.log("Migratsiya muvaffaqiyatli:",summary)}finally{if(source)await source.end();if(dump)await dump.close();await target.end()}
